#define PY_SSIZE_T_CLEAN
#include <Python.h>
#include <sqlite3.h>


#define ADD_INT_CONST(mod, name) \
    do { \
        if (PyModule_AddIntConstant((mod), #name, (name)) < 0) { \
            return NULL; \
        } \
    } while (0)

#define ADD_STR_CONST(mod, name) \
    do { \
        if (PyModule_AddStringConstant((mod), #name, (name)) < 0) { \
            return NULL; \
        } \
    } while (0)


static struct PyModuleDef moduledef = {
    PyModuleDef_HEAD_INIT,
    "cysqlite._constants",
    "sqlite3 constants",
    -1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};

PyMODINIT_FUNC
PyInit__constants(void)
{
    PyObject *m = PyModule_Create(&moduledef);
    if (!m) {
        return NULL;
    }

    /* Version */
    ADD_STR_CONST(m, SQLITE_VERSION);
    ADD_INT_CONST(m, SQLITE_VERSION_NUMBER);

    /* Other sqlite constants */
    ADD_INT_CONST(m, SQLITE_ROW);
    ADD_INT_CONST(m, SQLITE_OK);
    ADD_INT_CONST(m, SQLITE_ERROR);
    ADD_INT_CONST(m, SQLITE_INTERNAL);
    ADD_INT_CONST(m, SQLITE_PERM);
    ADD_INT_CONST(m, SQLITE_ABORT);
    ADD_INT_CONST(m, SQLITE_BUSY);
    ADD_INT_CONST(m, SQLITE_LOCKED);
    ADD_INT_CONST(m, SQLITE_NOMEM);
    ADD_INT_CONST(m, SQLITE_READONLY);
    ADD_INT_CONST(m, SQLITE_INTERRUPT);
    ADD_INT_CONST(m, SQLITE_IOERR);
    ADD_INT_CONST(m, SQLITE_CORRUPT);
    ADD_INT_CONST(m, SQLITE_NOTFOUND);
    ADD_INT_CONST(m, SQLITE_FULL);
    ADD_INT_CONST(m, SQLITE_CANTOPEN);
    ADD_INT_CONST(m, SQLITE_PROTOCOL);
    ADD_INT_CONST(m, SQLITE_EMPTY);
    ADD_INT_CONST(m, SQLITE_SCHEMA);
    ADD_INT_CONST(m, SQLITE_TOOBIG);
    ADD_INT_CONST(m, SQLITE_CONSTRAINT);
    ADD_INT_CONST(m, SQLITE_MISMATCH);
    ADD_INT_CONST(m, SQLITE_MISUSE);
    ADD_INT_CONST(m, SQLITE_NOLFS);
    ADD_INT_CONST(m, SQLITE_AUTH);
    ADD_INT_CONST(m, SQLITE_FORMAT);
    ADD_INT_CONST(m, SQLITE_RANGE);
    ADD_INT_CONST(m, SQLITE_NOTADB);
    ADD_INT_CONST(m, SQLITE_ROW);
    ADD_INT_CONST(m, SQLITE_DONE);

    ADD_INT_CONST(m, SQLITE_STATUS_MEMORY_USED);
    ADD_INT_CONST(m, SQLITE_STATUS_PAGECACHE_USED);
    ADD_INT_CONST(m, SQLITE_STATUS_PAGECACHE_OVERFLOW);
    ADD_INT_CONST(m, SQLITE_STATUS_SCRATCH_USED);
    ADD_INT_CONST(m, SQLITE_STATUS_SCRATCH_OVERFLOW);
    ADD_INT_CONST(m, SQLITE_STATUS_MALLOC_SIZE);
    ADD_INT_CONST(m, SQLITE_STATUS_PARSER_STACK);
    ADD_INT_CONST(m, SQLITE_STATUS_PAGECACHE_SIZE);
    ADD_INT_CONST(m, SQLITE_STATUS_SCRATCH_SIZE);
    ADD_INT_CONST(m, SQLITE_STATUS_MALLOC_COUNT);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_LOOKASIDE_USED);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_CACHE_USED);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_SCHEMA_USED);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_STMT_USED);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_LOOKASIDE_HIT);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_CACHE_HIT);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_CACHE_MISS);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_CACHE_WRITE);
    ADD_INT_CONST(m, SQLITE_DBSTATUS_DEFERRED_FKS);

    ADD_INT_CONST(m, SQLITE_DBCONFIG_MAINDBNAME);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_FKEY);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_TRIGGER);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_QPSG);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_TRIGGER_EQP);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_RESET_DATABASE);
#if SQLITE_VERSION_NUMBER >= 3026000
    ADD_INT_CONST(m, SQLITE_DBCONFIG_DEFENSIVE);
#endif
#if SQLITE_VERSION_NUMBER >= 3028000
    ADD_INT_CONST(m, SQLITE_DBCONFIG_WRITABLE_SCHEMA);
#endif
#if SQLITE_VERSION_NUMBER >= 3029000
    ADD_INT_CONST(m, SQLITE_DBCONFIG_DQS_DDL);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_DQS_DML);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_LEGACY_ALTER_TABLE);
#endif
#if SQLITE_VERSION_NUMBER >= 3030000
    ADD_INT_CONST(m, SQLITE_DBCONFIG_ENABLE_VIEW);
#endif
#if SQLITE_VERSION_NUMBER >= 3031000
    ADD_INT_CONST(m, SQLITE_DBCONFIG_LEGACY_FILE_FORMAT);
    ADD_INT_CONST(m, SQLITE_DBCONFIG_TRUSTED_SCHEMA);
#endif

    ADD_INT_CONST(m, SQLITE_CREATE_INDEX);
    ADD_INT_CONST(m, SQLITE_CREATE_TABLE);
    ADD_INT_CONST(m, SQLITE_CREATE_TEMP_INDEX);
    ADD_INT_CONST(m, SQLITE_CREATE_TEMP_TABLE);
    ADD_INT_CONST(m, SQLITE_CREATE_TEMP_TRIGGER);
    ADD_INT_CONST(m, SQLITE_CREATE_TEMP_VIEW);
    ADD_INT_CONST(m, SQLITE_CREATE_TRIGGER);
    ADD_INT_CONST(m, SQLITE_CREATE_VIEW);
    ADD_INT_CONST(m, SQLITE_DELETE);
    ADD_INT_CONST(m, SQLITE_DROP_INDEX);
    ADD_INT_CONST(m, SQLITE_DROP_TABLE);
    ADD_INT_CONST(m, SQLITE_DROP_TEMP_INDEX);
    ADD_INT_CONST(m, SQLITE_DROP_TEMP_TABLE);
    ADD_INT_CONST(m, SQLITE_DROP_TEMP_TRIGGER);
    ADD_INT_CONST(m, SQLITE_DROP_TEMP_VIEW);
    ADD_INT_CONST(m, SQLITE_DROP_TRIGGER);
    ADD_INT_CONST(m, SQLITE_DROP_VIEW);
    ADD_INT_CONST(m, SQLITE_INSERT);
    ADD_INT_CONST(m, SQLITE_PRAGMA);
    ADD_INT_CONST(m, SQLITE_READ);
    ADD_INT_CONST(m, SQLITE_SELECT);
    ADD_INT_CONST(m, SQLITE_TRANSACTION);
    ADD_INT_CONST(m, SQLITE_UPDATE);
    ADD_INT_CONST(m, SQLITE_ATTACH);
    ADD_INT_CONST(m, SQLITE_DETACH);
    ADD_INT_CONST(m, SQLITE_ALTER_TABLE);
    ADD_INT_CONST(m, SQLITE_REINDEX);
    ADD_INT_CONST(m, SQLITE_ANALYZE);
    ADD_INT_CONST(m, SQLITE_CREATE_VTABLE);
    ADD_INT_CONST(m, SQLITE_DROP_VTABLE);
    ADD_INT_CONST(m, SQLITE_FUNCTION);
    ADD_INT_CONST(m, SQLITE_SAVEPOINT);
    ADD_INT_CONST(m, SQLITE_COPY);
    ADD_INT_CONST(m, SQLITE_RECURSIVE);
    ADD_INT_CONST(m, SQLITE_DENY);
    ADD_INT_CONST(m, SQLITE_IGNORE);

    ADD_INT_CONST(m, SQLITE_OPEN_READONLY);
    ADD_INT_CONST(m, SQLITE_OPEN_READWRITE);
    ADD_INT_CONST(m, SQLITE_OPEN_CREATE);
    ADD_INT_CONST(m, SQLITE_OPEN_DELETEONCLOSE);
    ADD_INT_CONST(m, SQLITE_OPEN_EXCLUSIVE);
    ADD_INT_CONST(m, SQLITE_OPEN_AUTOPROXY);
    ADD_INT_CONST(m, SQLITE_OPEN_URI);
    ADD_INT_CONST(m, SQLITE_OPEN_MEMORY);
    ADD_INT_CONST(m, SQLITE_OPEN_MAIN_DB);
    ADD_INT_CONST(m, SQLITE_OPEN_TEMP_DB);
    ADD_INT_CONST(m, SQLITE_OPEN_TRANSIENT_DB);
    ADD_INT_CONST(m, SQLITE_OPEN_MAIN_JOURNAL);
    ADD_INT_CONST(m, SQLITE_OPEN_TEMP_JOURNAL);
    ADD_INT_CONST(m, SQLITE_OPEN_SUBJOURNAL);
    ADD_INT_CONST(m, SQLITE_OPEN_MASTER_JOURNAL);
    ADD_INT_CONST(m, SQLITE_OPEN_NOMUTEX);
    ADD_INT_CONST(m, SQLITE_OPEN_FULLMUTEX);
    ADD_INT_CONST(m, SQLITE_OPEN_SHAREDCACHE);
    ADD_INT_CONST(m, SQLITE_OPEN_PRIVATECACHE);
    ADD_INT_CONST(m, SQLITE_OPEN_WAL);

    ADD_INT_CONST(m, SQLITE_LIMIT_LENGTH);
    ADD_INT_CONST(m, SQLITE_LIMIT_SQL_LENGTH);
    ADD_INT_CONST(m, SQLITE_LIMIT_COLUMN);
    ADD_INT_CONST(m, SQLITE_LIMIT_EXPR_DEPTH);
    ADD_INT_CONST(m, SQLITE_LIMIT_COMPOUND_SELECT);
    ADD_INT_CONST(m, SQLITE_LIMIT_VDBE_OP);
    ADD_INT_CONST(m, SQLITE_LIMIT_FUNCTION_ARG);
    ADD_INT_CONST(m, SQLITE_LIMIT_ATTACHED);
    ADD_INT_CONST(m, SQLITE_LIMIT_LIKE_PATTERN_LENGTH);
    ADD_INT_CONST(m, SQLITE_LIMIT_VARIABLE_NUMBER);
    ADD_INT_CONST(m, SQLITE_LIMIT_TRIGGER_DEPTH);
    ADD_INT_CONST(m, SQLITE_LIMIT_WORKER_THREADS);

    ADD_INT_CONST(m, SQLITE_TRACE_STMT);
    ADD_INT_CONST(m, SQLITE_TRACE_PROFILE);
    ADD_INT_CONST(m, SQLITE_TRACE_ROW);
    ADD_INT_CONST(m, SQLITE_TRACE_CLOSE);

    ADD_INT_CONST(m, SQLITE_FCNTL_LOCKSTATE);
    ADD_INT_CONST(m, SQLITE_FCNTL_GET_LOCKPROXYFILE);
    ADD_INT_CONST(m, SQLITE_FCNTL_SET_LOCKPROXYFILE);
    ADD_INT_CONST(m, SQLITE_FCNTL_LAST_ERRNO);
    ADD_INT_CONST(m, SQLITE_FCNTL_SIZE_HINT);
    ADD_INT_CONST(m, SQLITE_FCNTL_CHUNK_SIZE);
    ADD_INT_CONST(m, SQLITE_FCNTL_FILE_POINTER);
    ADD_INT_CONST(m, SQLITE_FCNTL_SYNC_OMITTED);
    ADD_INT_CONST(m, SQLITE_FCNTL_WIN32_AV_RETRY);
    ADD_INT_CONST(m, SQLITE_FCNTL_PERSIST_WAL);
    ADD_INT_CONST(m, SQLITE_FCNTL_OVERWRITE);
    ADD_INT_CONST(m, SQLITE_FCNTL_VFSNAME);
    ADD_INT_CONST(m, SQLITE_FCNTL_POWERSAFE_OVERWRITE);
    ADD_INT_CONST(m, SQLITE_FCNTL_PRAGMA);
    ADD_INT_CONST(m, SQLITE_FCNTL_BUSYHANDLER);
    ADD_INT_CONST(m, SQLITE_FCNTL_TEMPFILENAME);
    ADD_INT_CONST(m, SQLITE_FCNTL_MMAP_SIZE);
    ADD_INT_CONST(m, SQLITE_FCNTL_TRACE);
    ADD_INT_CONST(m, SQLITE_FCNTL_HAS_MOVED);
    ADD_INT_CONST(m, SQLITE_FCNTL_SYNC);
    ADD_INT_CONST(m, SQLITE_FCNTL_COMMIT_PHASETWO);
    ADD_INT_CONST(m, SQLITE_FCNTL_WIN32_SET_HANDLE);
    ADD_INT_CONST(m, SQLITE_FCNTL_WAL_BLOCK);
    ADD_INT_CONST(m, SQLITE_FCNTL_ZIPVFS);
    ADD_INT_CONST(m, SQLITE_FCNTL_RBU);
    ADD_INT_CONST(m, SQLITE_FCNTL_VFS_POINTER);
    ADD_INT_CONST(m, SQLITE_FCNTL_JOURNAL_POINTER);
    ADD_INT_CONST(m, SQLITE_FCNTL_WIN32_GET_HANDLE);
    ADD_INT_CONST(m, SQLITE_FCNTL_PDB);
    ADD_INT_CONST(m, SQLITE_FCNTL_BEGIN_ATOMIC_WRITE);
    ADD_INT_CONST(m, SQLITE_FCNTL_COMMIT_ATOMIC_WRITE);
    ADD_INT_CONST(m, SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE);
    ADD_INT_CONST(m, SQLITE_FCNTL_LOCK_TIMEOUT);
    ADD_INT_CONST(m, SQLITE_FCNTL_DATA_VERSION);
#if SQLITE_VERSION_NUMBER >= 3027000
    ADD_INT_CONST(m, SQLITE_FCNTL_SIZE_LIMIT);
#endif
#if SQLITE_VERSION_NUMBER >= 3032000
    ADD_INT_CONST(m, SQLITE_FCNTL_CKPT_DONE);
    ADD_INT_CONST(m, SQLITE_FCNTL_RESERVE_BYTES);
    ADD_INT_CONST(m, SQLITE_FCNTL_CKPT_START);
#endif
#if SQLITE_VERSION_NUMBER >= 3036000
    ADD_INT_CONST(m, SQLITE_FCNTL_EXTERNAL_READER);
#endif
#if SQLITE_VERSION_NUMBER >= 3040000
    ADD_INT_CONST(m, SQLITE_FCNTL_CKSM_FILE);
#endif
#if SQLITE_VERSION_NUMBER >= 3041000
    ADD_INT_CONST(m, SQLITE_FCNTL_RESET_CACHE);
#endif
#if SQLITE_VERSION_NUMBER >= 3048000
    ADD_INT_CONST(m, SQLITE_FCNTL_NULL_IO);
#endif

    ADD_INT_CONST(m, SQLITE_CHECKPOINT_PASSIVE);
    ADD_INT_CONST(m, SQLITE_CHECKPOINT_FULL);
    ADD_INT_CONST(m, SQLITE_CHECKPOINT_RESTART);
    ADD_INT_CONST(m, SQLITE_CHECKPOINT_TRUNCATE);

    return m;
}
