from typing import (
    Any,
    Callable,
    ClassVar,
    Iterator,
    Mapping,
    Protocol,
    Sequence,
    overload,
)
from collections.abc import Buffer

__all__ = [
    "Blob",
    "Connection",
    "Cursor",
    "Row",
    "TableFunction",
    "compile_option",
    "connect",
    "damerau_levenshtein_dist",
    "dict_factory",
    "levenshtein_dist",
    "median",
    "rank_bm25",
    "rank_lucene",
    "sqlite_version",
    "sqlite_version_info",
    "status",
    "threadsafety",
    "vfs_list",
]

# ---------------------------------------------------------------------------
# Module-level constants

sqlite_version: str
sqlite_version_info: tuple[int, int, int]
threadsafety: int
HAS_COLUMN_METADATA: bool
HAS_DESERIALIZE: bool

# ---------------------------------------------------------------------------
# Type aliases

_Params = Sequence[Any] | Mapping[str, Any]
_RowFactory = Callable[["Cursor", tuple[Any, ...]], Any]
_TraceCallback = Callable[[int, int, str, int], None]
_HookCallback = Callable[[], Any]
_UpdateCallback = Callable[[str, str, str, int], Any]
_AuthorizerCallback = Callable[[int, str | None, str | None, str | None, str | None], int]
_ProgressCallback = Callable[[], int | None]
_BackupProgress = Callable[[int, int, bool], None]
_Adapter = Callable[[Any], Any]
_Converter = Callable[[bytes | str | int | float], Any]

class _Aggregate(Protocol):
    def step(self, *args: Any) -> None: ...
    def finalize(self) -> Any: ...

class _WindowAggregate(Protocol):
    def step(self, *args: Any) -> None: ...
    def inverse(self, *args: Any) -> None: ...
    def value(self) -> Any: ...
    def finalize(self) -> Any: ...

# ---------------------------------------------------------------------------
# Module-level functions

def connect(
    database: str,
    flags: int | None = ...,
    timeout: float = ...,
    vfs: str | None = ...,
    uri: bool = ...,
    cached_statements: int = ...,
    extensions: bool = ...,
    row_factory: _RowFactory | None = ...,
    autoconnect: bool = ...,
    pragmas: Mapping[str, Any] | None = ...,
    journal_mode: str | None = ...,
) -> Connection: ...

def status(flag: int) -> tuple[int, int]: ...
def compile_option(opt: str) -> bool: ...
def complete_statement(sql: str) -> bool: ...
def vfs_list() -> list[str]: ...
def dict_factory(cursor: Cursor, row: tuple[Any, ...]) -> dict[str, Any]: ...

# Threading / global config
def set_singlethread() -> bool: ...
def set_multithread() -> bool: ...
def set_serialized() -> bool: ...
def set_lookaside(size: int, slots: int) -> bool: ...
def set_mmap_size(default_size: int, max_size: int) -> bool: ...
def set_stmt_journal_spill(nbytes: int) -> bool: ...

# Built-in UDFs
def rank_bm25(match_info: bytes, *weights: float) -> float: ...
def rank_lucene(match_info: bytes, *weights: float) -> float: ...
def levenshtein_dist(a: str, b: str) -> int: ...
def damerau_levenshtein_dist(a: str, b: str) -> int: ...

class median:
    def step(self, item: float) -> None: ...
    def inverse(self, item: float) -> None: ...
    def value(self) -> float: ...
    def finalize(self) -> float: ...

# ---------------------------------------------------------------------------
# Row

class Row:
    def __init__(self, cursor: Cursor, data: tuple[Any, ...]) -> None: ...
    @overload
    def __getitem__(self, key: int) -> Any: ...
    @overload
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: object) -> bool: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __ne__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = ...) -> Any: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[Any]: ...
    def items(self) -> list[tuple[str, Any]]: ...
    def as_dict(self) -> dict[str, Any]: ...

# ---------------------------------------------------------------------------
# Cursor

class Cursor:
    description: tuple[tuple[str, ...], ...] | None
    lastrowid: int | None
    rowcount: int
    row_factory: _RowFactory | None
    @property
    def conn(self) -> Connection: ...
    def execute(self, sql: str, params: _Params | None = ...) -> Cursor: ...
    def executemany(self, sql: str, seq_of_params: Sequence[_Params] | None = ...) -> Cursor: ...
    def executescript(self, sql: str) -> Cursor: ...
    def fetchone(self) -> Any | None: ...
    def fetchmany(self, size: int = ...) -> list[Any]: ...
    def fetchall(self) -> list[Any]: ...
    def scalar(self) -> Any: ...
    def columns(self) -> list[str]: ...
    def close(self) -> None: ...
    def __iter__(self) -> Cursor: ...
    def __next__(self) -> Any: ...
    def __enter__(self) -> Cursor: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

# ---------------------------------------------------------------------------
# Blob

class Blob:
    def __init__(
        self,
        conn: Connection,
        table: str,
        column: str,
        rowid: int,
        read_only: bool = ...,
        database: str | None = ...,
    ) -> None: ...
    @property
    def closed(self) -> bool: ...
    def close(self) -> None: ...
    def reopen(self, rowid: int) -> None: ...
    def read(self, size: int = ...) -> bytes: ...
    def readall(self) -> bytes: ...
    def readinto(self, b: bytearray | memoryview) -> int: ...
    def readline(self, size: int = ...) -> bytes: ...
    def readlines(self, hint: int = ...) -> list[bytes]: ...
    def write(self, data: bytes | Buffer) -> int: ...
    def writelines(self, lines: Sequence[bytes]) -> int: ...
    def seek(self, offset: int, whence: int = ...) -> int: ...
    def tell(self) -> int: ...
    def fileno(self) -> int: ...
    def flush(self) -> None: ...
    def isatty(self) -> bool: ...
    def readable(self) -> bool: ...
    def writable(self) -> bool: ...
    def seekable(self) -> bool: ...
    def truncate(self, size: int | None = ...) -> int: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: int) -> int: ...
    @overload
    def __getitem__(self, key: slice) -> bytes: ...
    @overload
    def __setitem__(self, key: int, value: int) -> None: ...
    @overload
    def __setitem__(self, key: slice, value: bytes | Buffer) -> None: ...
    def __iter__(self) -> Iterator[bytes]: ...
    def __next__(self) -> bytes: ...
    def __enter__(self) -> Blob: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

# ---------------------------------------------------------------------------
# Transactions

class Transaction:
    def __init__(self, conn: Connection, lock: str | None = ...) -> None: ...
    def commit(self, begin: bool = ...) -> None: ...
    def rollback(self, begin: bool = ...) -> None: ...
    def __enter__(self) -> Transaction: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool | None: ...
    def __call__(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...

class Savepoint:
    def __init__(self, conn: Connection, sid: str | None = ...) -> None: ...
    def commit(self, begin: bool = ...) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Savepoint: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool | None: ...
    def __call__(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...

class Atomic:
    def __init__(self, conn: Connection, lock: str | None = ...) -> None: ...
    def commit(self, begin: bool = ...) -> None: ...
    def rollback(self) -> None: ...
    def __enter__(self) -> Transaction | Savepoint: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> bool | None: ...
    def __call__(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...

# ---------------------------------------------------------------------------
# TableFunction

class TableFunction:
    columns: ClassVar[list[str | tuple[str, str]]]
    params: ClassVar[list[str]]
    name: ClassVar[str | None]
    with_rowid: ClassVar[bool]
    print_tracebacks: ClassVar[bool]
    @classmethod
    def register(cls, conn: Connection) -> None: ...
    @classmethod
    def from_function(
        cls,
        fn: Callable[..., Any],
        name: str | None = ...,
        columns: Sequence[str | tuple[str, str]] | None = ...,
        params: Sequence[str] | None = ...,
    ) -> type[TableFunction]: ...
    @classmethod
    def get_table_columns_declaration(cls) -> str: ...
    def initialize(self, **filters: Any) -> None: ...
    def iterate(self, idx: int) -> tuple[Any, ...]: ...
    def insert(self, rowid: int, values: tuple[Any, ...]) -> int: ...
    def update(self, old_rowid: int, new_rowid: int, values: tuple[Any, ...]) -> None: ...
    def delete(self, rowid: int) -> None: ...

# ---------------------------------------------------------------------------
# Connection

class Connection:
    extensions: bool
    uri: bool
    cached_statements: int
    flags: int
    timeout: float
    database: str
    vfs: str | None
    row_factory: _RowFactory | None
    print_callback_tracebacks: bool
    pragmas: dict[str, Any]

    def __init__(
        self,
        database: str,
        flags: int | None = ...,
        timeout: float = ...,
        vfs: str | None = ...,
        uri: bool = ...,
        cached_statements: int = ...,
        extensions: bool = ...,
        row_factory: _RowFactory | None = ...,
        autoconnect: bool = ...,
        pragmas: Mapping[str, Any] | None = ...,
        journal_mode: str | None = ...,
    ) -> None: ...

    # Lifecycle
    def connect(self) -> bool: ...
    def close(self, force: bool = ...) -> bool: ...
    def is_closed(self) -> bool: ...
    def interrupt(self) -> None: ...
    def __enter__(self) -> Connection: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    def __call__(self, fn: Callable[..., Any]) -> Callable[..., Any]: ...

    # Execution
    def cursor(self) -> Cursor: ...
    def execute(self, sql: str, params: _Params | None = ...) -> Cursor: ...
    def executemany(self, sql: str, seq_of_params: Sequence[_Params] | None = ...) -> Cursor: ...
    def executescript(self, sql: str) -> Cursor: ...
    def execute_one(self, sql: str, params: _Params | None = ...) -> Any | None: ...
    def execute_scalar(self, sql: str, params: _Params | None = ...) -> Any: ...
    def execute_simple(self, sql: str, callback: Callable[..., Any] | None = ...) -> None: ...

    # Counters / state
    def changes(self) -> int: ...
    def total_changes(self) -> int: ...
    def last_insert_rowid(self) -> int: ...
    def autocommit(self) -> bool: ...
    @property
    def in_transaction(self) -> bool: ...

    # Transactions
    def begin(self, lock: str | None = ...) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def transaction(self, lock: str | None = ...) -> Transaction: ...
    def savepoint(self, sid: str | None = ...) -> Savepoint: ...
    def atomic(self, lock: str | None = ...) -> Atomic: ...

    # Pragma
    def pragma(
        self,
        key: str,
        value: Any = ...,
        database: str | None = ...,
        multi: bool = ...,
        permanent: bool = ...,
    ) -> Any: ...

    # Hooks
    def commit_hook(self, fn: _HookCallback | None) -> None: ...
    def rollback_hook(self, fn: _HookCallback | None) -> None: ...
    def update_hook(self, fn: _UpdateCallback | None) -> None: ...
    def authorizer(self, fn: _AuthorizerCallback | None) -> None: ...
    def trace(self, fn: _TraceCallback | None, mask: int = ..., expand_sql: bool = ...) -> None: ...
    def progress(self, fn: _ProgressCallback | None, n: int = ...) -> None: ...
    def set_busy_handler(self, timeout: float = ...) -> None: ...

    # User-defined
    def create_function(
        self,
        fn: Callable[..., Any] | None,
        name: str | None = ...,
        nargs: int = ...,
        deterministic: bool = ...,
    ) -> None: ...
    def create_aggregate(
        self,
        agg: type[_Aggregate] | None,
        name: str | None = ...,
        nargs: int = ...,
        deterministic: bool = ...,
    ) -> None: ...
    def create_window_function(
        self,
        agg: type[_WindowAggregate] | None,
        name: str | None = ...,
        nargs: int = ...,
        deterministic: bool = ...,
    ) -> None: ...
    def create_collation(self, fn: Callable[[str, str], int] | None, name: str | None = ...) -> None: ...
    def create_table_function(
        self,
        fn: Callable[..., Any],
        name: str | None = ...,
        columns: Sequence[str | tuple[str, str]] | None = ...,
        params: Sequence[str] | None = ...,
    ) -> type[TableFunction]: ...
    def table_function(
        self,
        name: str | None = ...,
        columns: Sequence[str | tuple[str, str]] | None = ...,
        params: Sequence[str] | None = ...,
    ) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

    # Type system
    def register_adapter(self, python_type: type, fn: _Adapter) -> None: ...
    def unregister_adapter(self, python_type: type) -> None: ...
    def adapter(self, python_type: type) -> Callable[[_Adapter], _Adapter]: ...
    def register_converter(self, data_type: str, fn: _Converter) -> None: ...
    def unregister_converter(self, data_type: str) -> None: ...
    def converter(self, data_type: str) -> Callable[[_Converter], _Converter]: ...
    def register_type(
        self,
        data_type: str | None = ...,
        converter: _Converter | None = ...,
        python_type: type | None = ...,
        adapter: _Adapter | None = ...,
    ) -> None: ...

    # Introspection
    def get_tables(self, database: str | None = ...) -> list[str]: ...
    def get_views(self, database: str | None = ...) -> list[Any]: ...
    def get_indexes(self, table: str, database: str | None = ...) -> list[Any]: ...
    def get_columns(self, table: str, database: str | None = ...) -> list[Any]: ...
    def get_primary_keys(self, table: str, database: str | None = ...) -> list[str]: ...
    def get_foreign_keys(self, table: str, database: str | None = ...) -> list[Any]: ...
    def table_column_metadata(
        self,
        table: str,
        column: str,
        database: str | None = ...,
    ) -> tuple[str, str, str, str, int, int, int]: ...
    def database_list(self) -> list[tuple[str, str]]: ...

    # Persistence
    def backup(
        self,
        dest: Connection,
        pages: int | None = ...,
        name: str | None = ...,
        progress: _BackupProgress | None = ...,
        src_name: str | None = ...,
        dest_name: str | None = ...,
    ) -> None: ...
    def backup_to_file(
        self,
        filename: str,
        pages: int | None = ...,
        name: str | None = ...,
        progress: _BackupProgress | None = ...,
        src_name: str | None = ...,
        dest_name: str | None = ...,
    ) -> None: ...
    def serialize(self, name: str = ...) -> bytes: ...
    def deserialize(self, data: bytes | Buffer, name: str = ...) -> None: ...
    def checkpoint(
        self,
        full: bool = ...,
        truncate: bool = ...,
        restart: bool = ...,
        name: str | None = ...,
    ) -> tuple[int, int]: ...
    def set_autocheckpoint(self, n: int) -> None: ...
    def optimize(
        self,
        debug: bool = ...,
        run_tables: bool = ...,
        set_limit: bool = ...,
        check_table_sizes: bool = ...,
        dry_run: bool = ...,
    ) -> None: ...

    # Multi-database
    def attach(self, filename: str, name: str) -> None: ...
    def detach(self, name: str) -> None: ...
    def set_main_db_name(self, name: str) -> None: ...

    # BLOB
    def blob_open(
        self,
        table: str,
        column: str,
        rowid: int,
        read_only: bool = ...,
        database: str | None = ...,
    ) -> Blob: ...

    # Configuration
    def db_config(self, op: int, setting: int | None = ...) -> int: ...
    def setlimit(self, category: int, limit: int) -> int: ...
    def getlimit(self, category: int) -> int: ...
    def file_control(self, op: int, val: int, name: str | None = ...) -> int: ...
    def set_foreign_keys_enabled(self, enabled: int = ...) -> None: ...
    def get_foreign_keys_enabled(self) -> int: ...
    def set_triggers_enabled(self, enabled: int = ...) -> None: ...
    def get_triggers_enabled(self) -> int: ...
    def set_load_extension(self, enabled: int = ...) -> None: ...
    def get_load_extension(self) -> int: ...
    def set_shared_cache(self, enabled: bool) -> None: ...
    def load_extension(self, name: str) -> None: ...

    # Diagnostics
    def status(self, flag: int) -> tuple[int, int]: ...
    def get_stmt_usage(self) -> tuple[int, int]: ...
    def finalize_statements(self) -> None: ...
    @property
    def callback_error(self) -> BaseException | None: ...
